/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'mehran-bg': '#FBF4E6',
        'mehran-surface': '#FBF4E6',
        'mehran-surface-bright': '#FFFFFF',
        'mehran-surface-variant': '#E3D2A8',
        'mehran-surface-container': '#FFFBF0',
        'mehran-surface-container-high': '#FFFFFF',
        'mehran-surface-container-low': '#F5E8CB',
        'mehran-surface-container-lowest': '#F0DFB8',
        'mehran-on-bg': '#2B1B0E',
        'mehran-on-surface': '#2B1B0E',
        'mehran-on-surface-variant': '#6B4A2E',
        'mehran-primary': '#C1272D',
        'mehran-primary-container': '#A32D2D',
        'mehran-on-primary': '#FFFFFF',
        'mehran-on-primary-container': '#FFFFFF',
        'mehran-secondary': '#B8860B',
        'mehran-secondary-container': '#F0C02E',
        'mehran-on-secondary': '#3E2E00',
        'mehran-on-secondary-container': '#4D3B00',
        'mehran-tertiary': '#B4A98F',
        'mehran-tertiary-container': '#D8CBA8',
        'mehran-on-tertiary': '#3B2F1A',
        'mehran-on-tertiary-container': '#2B2013',
        'mehran-tertiary-fixed': '#EFE3C8',
        'mehran-on-tertiary-fixed': '#2B2013',
        'mehran-on-tertiary-fixed-variant': '#6B5847',
        'mehran-outline': '#A8785F',
        'mehran-outline-variant': '#D9C39B',
        'mehran-error': '#B3261E',
        'mehran-error-container': '#F9DEDC',
        'mehran-on-error': '#FFFFFF',
        'mehran-on-error-container': '#410E0B',
        'mehran-inverse-primary': '#3B6D11',
        'mehran-inverse-surface': '#2B1B0E',
        'mehran-inverse-on-surface': '#FBF4E6',
        'mehran-cream': '#FDF6E3',
      },
      fontFamily: {
        jakarta: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      borderRadius: {
        'mehran': '0.75rem',
      },
    },
  },
  plugins: [],
};
